import { useMemo,useState } from 'react';
import { Activity,BrainCircuit,ChevronDown,ChevronRight,Copy,FlaskConical,Github,KeyRound,LockKeyhole,ShieldCheck,Sparkles,UnlockKeyhole,WandSparkles,Zap } from 'lucide-react';
import { analyzeCipher,transformText } from './lib/api';
import type { AnalysisResponse,TransformAlgorithm,TransformMode } from './types';
import { ResultCard } from './components/ResultCard';
import { Xray } from './components/Xray';

const examples=[['Base64','SGVsbG8gV29ybGQ='],['Caesar','Khoor Zruog'],['ROT13','Uryyb Jbeyq'],['Hex','48656c6c6f20576f726c64'],['Nested','U0dWc2JHOD0='],['Hindi','नमस्ते दुनिया']] as const;
const algos:[TransformAlgorithm,string][]=[['vigenere','Vigenère'],['caesar','Caesar'],['rot13','ROT13'],['atbash','Atbash'],['base64','Base64'],['hex','Hex'],['xor','XOR'],['aes-gcm','AES-256-GCM']];

export default function App(){
 const [tab,setTab]=useState<'magic'|'transform'>('magic');
 const [input,setInput]=useState(''); const [key,setKey]=useState(''); const [depth,setDepth]=useState(3); const [advanced,setAdvanced]=useState(false);
 const [result,setResult]=useState<AnalysisResponse|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const [mode,setMode]=useState<TransformMode>('decrypt'); const [algorithm,setAlgorithm]=useState<TransformAlgorithm>('vigenere'); const [shift,setShift]=useState(3); const [output,setOutput]=useState('');
 const chars=useMemo(()=>[...input].length,[input]);
 async function runMagic(){if(!input.trim())return;setLoading(true);setError('');try{setResult(await analyzeCipher(input,depth,key))}catch(e){setError(e instanceof Error?e.message:'Analysis failed')}finally{setLoading(false)}}
 async function runTransform(){if(!input.length)return;setLoading(true);setError('');try{const r=await transformText(input,mode,algorithm,key,shift);setOutput(r.output)}catch(e){setError(e instanceof Error?e.message:'Transform failed')}finally{setLoading(false)}}
 function load(v:string){setInput(v);setKey('');setResult(null);setOutput('');setError('')}
 return <div className="app-shell">
  <div className="aurora a"/><div className="aurora b"/><div className="aurora c"/><div className="grid-bg"/><div className="scanline"/>
  <header className="topbar"><div className="brand"><div className="brand-mark"><WandSparkles size={19}/></div><div><b>MAGICCIPHER</b><span>STUDIO V4</span></div></div><nav><button onClick={()=>setTab('magic')} className={tab==='magic'?'active':''}>Magic</button><button onClick={()=>setTab('transform')} className={tab==='transform'?'active':''}>Encrypt / Decrypt</button></nav><a className="github" href="https://github.com/itsyashXX/magiccipher" target="_blank" rel="noreferrer"><Github size={17}/> Source</a></header>
  <main>
   <section className="hero"><div className="hero-badge"><span className="pulse"/> V4 · DEEP CIPHER INTELLIGENCE</div><h1>Decode the unknown.<br/><span>Without pretending.</span></h1><p>Automatic detection, deeper classical-cipher search, multilingual evidence scoring and a direct encrypt/decrypt lab — wrapped in a faster, cleaner investigation workflow.</p><div className="hero-stats"><div><b>2,500+</b><span>candidate budget</span></div><div><b>Vigenère</b><span>auto-analysis</span></div><div><b>AES-GCM</b><span>authenticated crypto</span></div><div><b>Unicode</b><span>multilingual</span></div></div></section>

   {tab==='magic'?<section className="workspace">
    <div className="workspace-head"><div><div className="eyebrow">MAGIC ANALYZER</div><h2>Paste first. Magic investigates.</h2><p className="subcopy">No key is required for normal analysis. If you already know one, add it under Advanced.</p></div></div>
    <div className="editor-grid"><div className="panel input-panel"><div className="panel-top"><span>UNKNOWN INPUT</span><span>{chars} chars</span></div><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder="Paste encoded, encrypted or suspicious text…" spellCheck={false}/>
      <div className="examples">{examples.map(([n,v])=><button key={n} onClick={()=>load(v)}>{n}</button>)}</div>
      <button className={`advanced-toggle ${advanced?'open':''}`} onClick={()=>setAdvanced(v=>!v)}><span><KeyRound size={15}/> Advanced analysis</span><ChevronDown size={16}/></button>
      {advanced&&<div className="advanced-panel"><label><span>Known key (optional)</span><input value={key} onChange={e=>setKey(e.target.value)} placeholder="Only if you already know the key"/></label><div className="depth-control"><span>Recursive depth</span>{[1,2,3,4,5].map(n=><button key={n} className={depth===n?'active':''} onClick={()=>setDepth(n)}>{n}</button>)}</div></div>}
      <button className="primary-btn" disabled={loading||!input.trim()} onClick={runMagic}>{loading?<><Activity className="spin" size={18}/> Searching candidate space…</>:<><Sparkles size={18}/> Run Magic <ChevronRight size={18}/></>}</button>{error&&<div className="error">{error}</div>}
    </div>
    <div className="panel overview"><div className="panel-top"><span>ENGINE STATUS</span><span className="online"><i/> READY</span></div>{!result?<div className="empty-state"><div className="brain-orbit"><BrainCircuit size={46}/></div><h3>Waiting for ciphertext</h3><p>Magic tests structured decoders first, then classical ciphers, Vigenère candidates, XOR and recursive chains. Weak guesses stay weak.</p><div className="mini-flow"><span>Detect</span><b>→</b><span>Test</span><b>→</b><span>Score</span><b>→</b><span>Rank</span></div></div>:<><div className="category"><span>Assessment</span><strong>{result.likelyCategory}</strong></div><div className="metrics"><div><span>Entropy</span><b>{result.entropy}</b></div><div><span>Tested</span><b>{result.meta.candidatesTested}</b></div><div><span>Time</span><b>{result.meta.elapsedMs}ms</b></div></div><div className="honesty"><ShieldCheck size={18}/><p>{result.best&&result.best.score>=70?'A supported candidate was found. Review its recipe and evidence below.':'No candidate has strong enough evidence to be treated as certain. Possible leads are still shown below.'}</p></div></>}</div></div>
   </section>:<section className="workspace">
    <div className="workspace-head transform-head"><div><div className="eyebrow">TRANSFORM LAB</div><h2>Encrypt and decrypt directly.</h2><p className="subcopy">Use this when you know the algorithm or key. Magic is for unknown data; this lab is deterministic.</p></div><div className="seg"><button className={mode==='encrypt'?'active':''} onClick={()=>setMode('encrypt')}><LockKeyhole size={16}/> Encrypt</button><button className={mode==='decrypt'?'active':''} onClick={()=>setMode('decrypt')}><UnlockKeyhole size={16}/> Decrypt</button></div></div>
    <div className="editor-grid"><div className="panel input-panel"><div className="panel-top"><span>{mode.toUpperCase()} INPUT</span><span>{chars} chars</span></div><textarea value={input} onChange={e=>setInput(e.target.value)} placeholder={mode==='encrypt'?'Type plaintext…':'Paste ciphertext…'} spellCheck={false}/><div className="form-grid"><label><span>Algorithm</span><select value={algorithm} onChange={e=>setAlgorithm(e.target.value as TransformAlgorithm)}>{algos.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label><span>Key / password</span><input value={key} onChange={e=>setKey(e.target.value)} placeholder="For keyed algorithms"/></label>{algorithm==='caesar'&&<label><span>Shift</span><input type="number" value={shift} onChange={e=>setShift(Number(e.target.value))}/></label>}</div><button className="primary-btn" disabled={loading||!input.length} onClick={runTransform}>{loading?<><Activity className="spin" size={18}/> Processing…</>:<><Zap size={18}/> {mode==='encrypt'?'Encrypt':'Decrypt'} · {algos.find(a=>a[0]===algorithm)?.[1]}</>}</button>{error&&<div className="error">{error}</div>}</div>
    <div className="panel output-panel"><div className="panel-top"><span>OUTPUT</span>{output&&<button className="copy" onClick={()=>navigator.clipboard.writeText(output)}><Copy size={15}/> Copy</button>}</div>{output?<pre>{output}</pre>:<div className="empty-state"><FlaskConical size={44}/><h3>No output yet</h3><p>Choose the algorithm, provide a key only where required, then run the operation.</p></div>}<div className="safety-note"><ShieldCheck size={18}/><p>AES-256-GCM output is authenticated. Wrong passwords or modified ciphertext fail instead of producing fake plaintext.</p></div></div></div>
   </section>}

   {tab==='magic'&&result&&<section className="results-section"><div className="section-heading"><div><div className="eyebrow">ANALYSIS RESULT</div><h2>{result.best&&result.best.score>=70?'Strongest supported candidate':'No certain decode — strongest leads'}</h2><p className="subcopy">Candidates are ranked by structural and language evidence, not by readability alone.</p></div></div>{result.best?<ResultCard candidate={result.best} primary/>:<div className="panel no-result"><h3>No defensible plaintext</h3><p>For keyed encryption, use the exact key in Transform Lab or open Advanced analysis.</p></div>}{result.alternatives.length>0&&<details className="alternatives-box"><summary>Show {result.alternatives.length} other possible leads <ChevronDown size={16}/></summary><div className="alternatives">{result.alternatives.map(c=><ResultCard key={c.id} candidate={c}/>)}</div></details>}<Xray steps={result.xray}/></section>}

   <section className="engine-section"><div className="eyebrow">V4 PIPELINE</div><h2>More search. Less noise.</h2><div className="flow-grid">{[['01','Recognize','Strong signatures such as Base64, Hex, URL, Binary and Morse receive structural evidence.'],['02','Crack','Caesar, Atbash, Affine, ROT47, keyboard shifts, XOR and Vigenère analysis generate candidates.'],['03','Recurse','Promising reversible outputs can be analyzed again for nested encodings.'],['04','Score','Word matches, script detection, character quality and cipher-specific evidence determine rank.'],['05','Separate','Weak speculative candidates are shown as leads, not presented as a successful decrypt.'],['06','Transform','Dedicated encrypt/decrypt mode handles known algorithms and passwords directly.']].map(([n,t,d])=><article key={n}><span>{n}</span><FlaskConical size={21}/><h3>{t}</h3><p>{d}</p></article>)}</div></section>
  </main>
  <footer><div className="brand"><div className="brand-mark"><WandSparkles size={17}/></div><div><b>MAGICCIPHER</b><span>STUDIO V4</span></div></div><p>Explainable cryptography workbench.</p><span>Engine v4.0</span></footer>
 </div>
}
