import React from 'react';
import {createRoot} from 'react-dom/client';
import {BrowserRouter,Routes,Route,NavLink,Link,useLocation,useNavigate} from 'react-router-dom';
import {motion,AnimatePresence} from 'framer-motion';
import {ArrowUpRight,ArrowRight,Menu,X,MapPin,CalendarDays,BriefcaseBusiness,Landmark,ShieldCheck,Phone,Mail,Clock3,Play,Images,ChevronDown,Download,ExternalLink,Quote,CheckCircle2} from 'lucide-react';
import './styles.css';

const nav=[['About','/about'],['Biography','/biography'],['Journey','/journey'],['Bhimtal','/bhimtal'],['Public Service','/public-service'],['Media','/media'],['Gallery','/gallery'],['Vision','/vision'],['Contact','/contact']];
const milestones=[
 {year:'1992–1993',title:'Student leadership',text:'Ram Singh Kaida began his political journey in student politics and became student union president at MBPG College in 1993.'},
 {year:'1990s',title:'Uttarakhand statehood movement',text:'He was associated with the movement for Uttarakhand statehood, a formative chapter in his public life.'},
 {year:'2003–2008',title:'Panchayat politics',text:'He remained active in local and panchayat politics, working around community-level issues and development.'},
 {year:'2012',title:'First Assembly contest',text:'He contested the Bhimtal Assembly election on a Congress ticket and was not elected.'},
 {year:'2017',title:'Independent MLA',text:'He contested Bhimtal as an independent candidate and won, beginning his first term as an MLA.'},
 {year:'2021',title:'Joined BJP',text:'He joined the Bharatiya Janata Party in October 2021.'},
 {year:'2022',title:'Re-elected from Bhimtal',text:'He won Bhimtal again on a BJP ticket, securing a second term as MLA.'},
 {year:'20 Mar 2026',title:'Cabinet responsibility',text:'He took oath as a cabinet minister in the Uttarakhand government during the cabinet expansion.'}
];
const stats=[['01','Constituency','Bhimtal'],['02','District','Nainital'],['03','State','Uttarakhand'],['04','Role','Cabinet Minister']];
const service=[
 ['Urban development','Focus on stronger, better-managed urban systems and civic services.'],
 ['Water & basic services','Public attention to drinking water, implementation and village-level needs.'],
 ['Roads & connectivity','Infrastructure and connectivity remain central to hill-region development.'],
 ['Local governance','Engagement with elected representatives and officials to surface local issues.'],
 ['Tourism & culture','Supporting the natural, cultural and tourism identity of the Kumaon region.'],
 ['Youth & community','A public-life narrative rooted in student leadership and local participation.']
];
function Shell({children}:{children:React.ReactNode}){
 const [open,setOpen]=React.useState(false); const loc=useLocation();
 React.useEffect(()=>setOpen(false),[loc.pathname]);
 return <div className="app"><div className="noise"/><header className="top"><div className="ticker"><span>UTTARAKHAND</span><i/> <span>PUBLIC SERVICE</span><i/> <span>BHIMTAL • NAINITAL</span></div><div className="navwrap"><Link to="/" className="brand"><span>RAM SINGH KAIDA</span><small>राम सिंह कैड़ा</small></Link><nav>{nav.map(([label,path])=><NavLink key={path} to={path} className={({isActive})=>isActive?'active':''}>{label}</NavLink>)}</nav><Link className="navcta" to="/contact">Get in touch <ArrowUpRight size={15}/></Link><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div></header>
 <AnimatePresence>{open&&<motion.div className="mobilemenu" initial={{opacity:0,y:-20}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-20}}>{nav.map(([label,path],i)=><motion.div initial={{opacity:0,x:-15}} animate={{opacity:1,x:0}} transition={{delay:i*.03}} key={path}><Link to={path}>{label}<ArrowRight size={17}/></Link></motion.div>)}</motion.div>}</AnimatePresence>
 <main><AnimatePresence mode="wait"><motion.div key={loc.pathname} initial={{opacity:0,y:18}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} transition={{duration:.32}}>{children}</motion.div></AnimatePresence></main>
 <footer><div><span className="eyebrow">PUBLIC SERVICE • UTTARAKHAND</span><h2>Service that stays<br/><em>close to the ground.</em></h2></div><div className="footerlinks">{nav.slice(0,6).map(([l,p])=><Link key={p} to={p}>{l}</Link>)}</div><div className="copyright">© {new Date().getFullYear()} Ram Singh Kaida • Public information profile</div></footer></div>
}
function Hero(){return <section className="hero"><div className="heroGlow g1"/><div className="heroGlow g2"/><div className="heroGrid"/><div className="heroCopy"><div className="eyebrow"><span>BHIMTAL</span><i/><span>UTTARAKHAND</span><i/><span>PUBLIC SERVICE</span></div><h1>Ram Singh <span>Kaida.</span></h1><p className="hindi">राम सिंह कैड़ा</p><p className="lead">A public-service profile documenting the journey from student leadership and the Uttarakhand movement to elected representation and cabinet responsibility.</p><div className="actions"><Link className="btn primary" to="/biography">Read biography <ArrowRight/></Link><Link className="btn ghost" to="/journey">Explore the journey <ArrowUpRight/></Link></div><div className="heroMeta"><span><CalendarDays/> Born 15 March 1974</span><span><MapPin/> Kaida village • Okhalkanda</span></div></div><div className="portraitWrap"><div className="orbit o1"/><div className="orbit o2"/><div className="portraitCard"><div className="portraitLabel">PUBLIC PROFILE <b>01 / 09</b></div><img src="/ram-singh-kaida-reference.jpg" alt="Ram Singh Kaida"/><div className="portraitFade"/></div><div className="portraitTag">Serving Bhimtal<br/><b>Serving Uttarakhand</b></div></div><div className="scrollHint"><span>SCROLL TO EXPLORE</span><ChevronDown/></div></section>}
function Home(){return <><Hero/><section className="quick"><div className="quickIntro"><span className="eyebrow">AT A GLANCE</span><h2>A public life,<br/><em>told in chapters.</em></h2></div>{stats.map(([n,l,v])=><div className="quickCard" key={n}><span>{n}</span><strong>{v}</strong><small>{l}</small></div>)}</section><section className="feature"><div className="featureText"><span className="eyebrow">01 / ABOUT</span><h2>From the hills<br/>to <em>public service.</em></h2><p>Born in Nainital district, Ram Singh Kaida’s public life developed through student politics, the statehood movement, panchayat-level engagement and electoral representation in Bhimtal.</p><Link className="textlink" to="/about">Discover the story <ArrowUpRight/></Link></div><div className="featurePanel"><div className="panelOrb"/><Landmark size={32}/><span>BHIMTAL</span><strong>Local roots.<br/>State responsibility.</strong><p>Explore the constituency, people and issues that shape the public-service narrative.</p><Link to="/bhimtal">Explore Bhimtal <ArrowRight/></Link></div></section><section className="journeyTease"><div className="sectionHead"><div><span className="eyebrow">02 / JOURNEY</span><h2>Eight chapters.<br/><em>One evolving public life.</em></h2></div><Link className="textlink" to="/journey">Full timeline <ArrowUpRight/></Link></div><div className="timeline">{milestones.slice(0,4).map((m,i)=><motion.div whileInView={{opacity:1,x:0}} initial={{opacity:0,x:-20}} viewport={{once:true}} className="timeItem" key={m.year}><span>{m.year}</span><div><b>{m.title}</b><p>{m.text}</p></div></motion.div>)}</div></section><section className="serviceBand"><div><span className="eyebrow">03 / PUBLIC SERVICE</span><h2>Work is measured<br/>by <em>what reaches people.</em></h2></div><div className="serviceGrid">{service.slice(0,4).map(([a,b])=><div key={a}><CheckCircle2/><b>{a}</b><p>{b}</p></div>)}</div></section></>}
function Page({eyebrow,title,children,accent=''}:{eyebrow:string,title:React.ReactNode,children:React.ReactNode,accent?:string}){return <section className={'page '+accent}><div className="pageHero"><div className="heroGlow g1"/><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><div className="pageRule"/></div>{children}</section>}
function About(){return <Page eyebrow="01 / ABOUT" title={<>A life shaped by <em>participation.</em></>}><div className="split"><div className="portraitSmall"><img src="/ram-singh-kaida-reference.jpg" alt="Ram Singh Kaida"/></div><div className="rich"><span className="eyebrow">THE BEGINNING</span><h2>Roots in Nainital. A path through public life.</h2><p>Ram Singh Kaida was born on 15 March 1974 in Kaida village in the Okhalkanda block of Nainital district. His political journey is described in public reporting as beginning in student politics, followed by participation in the Uttarakhand statehood movement and later work in panchayat politics.</p><p>He represented Bhimtal in the Uttarakhand Legislative Assembly as an independent in 2017 and was re-elected in 2022 on a BJP ticket. In March 2026, he was inducted into the Uttarakhand cabinet.</p><div className="quote"><Quote/><p>“The public record is not one moment; it is a sequence of responsibilities.”</p></div></div></div><div className="factGrid">{[['15 Mar 1974','Date of birth'],['1993','Student union president'],['2017','First elected MLA'],['2022','Re-elected from Bhimtal'],['2026','Cabinet minister'],['Bhimtal','Constituency']].map(x=><div key={x[1]}><strong>{x[0]}</strong><span>{x[1]}</span></div>)}</div></Page>}
function Biography(){return <Page eyebrow="02 / BIOGRAPHY" title={<>The story behind the <em>public profile.</em></>}><div className="bioIntro"><div><span className="eyebrow">BIOGRAPHY</span><h2>From student leadership to cabinet responsibility.</h2></div><p>Public reporting traces a career that moved through student representation, the Uttarakhand statehood movement, local governance, electoral politics and state-level responsibility.</p></div><div className="bioSections"><article><span>01</span><h3>Student politics</h3><p>He began his political journey in the early 1990s and became student union president at MBPG College in 1993.</p></article><article><span>02</span><h3>Statehood movement</h3><p>His early public life included participation in the movement for Uttarakhand statehood.</p></article><article><span>03</span><h3>Local governance</h3><p>From 2003 to 2008, he was active in panchayat politics, connecting local issues with public representation.</p></article><article><span>04</span><h3>Electoral representation</h3><p>After a 2012 Assembly contest, he won Bhimtal as an independent in 2017 and returned as a BJP MLA in 2022.</p></article><article><span>05</span><h3>Cabinet role</h3><p>On 20 March 2026, he took oath as a cabinet minister in Uttarakhand’s expanded council of ministers.</p></article></div><div className="sources"><span className="eyebrow">REFERENCE NOTE</span><p>Dates and career milestones are based on public government and news sources; this page is an informational profile and not an official government portal.</p></div></Page>}
function Journey(){return <Page eyebrow="03 / JOURNEY" title={<>Eight chapters of <em>public life.</em></>}><div className="fullTimeline">{milestones.map((m,i)=><motion.div whileInView={{opacity:1,y:0}} initial={{opacity:0,y:20}} viewport={{once:true,amount:.2}} className="chapter" key={m.year}><div className="chapterNo">0{i+1}</div><div className="chapterYear">{m.year}</div><div className="chapterBody"><h2>{m.title}</h2><p>{m.text}</p></div></motion.div>)}</div></Page>}
function Bhimtal(){return <Page eyebrow="04 / BHIMTAL" title={<>The constituency at the <em>centre.</em></>}><div className="placeHero"><div><span className="eyebrow">BHIMTAL • NAINITAL</span><h2>Lake country.<br/><em>Mountain communities.</em></h2><p>Bhimtal is a hill constituency in Nainital district. The public-service story here intersects with water, roads, local governance, tourism, agriculture and access to basic services.</p><Link className="btn primary" to="/public-service">Explore service priorities <ArrowRight/></Link></div><div className="placeVisual"><div className="mountain m1"/><div className="mountain m2"/><div className="lake"/><MapPin/></div></div><div className="issueGrid">{['Drinking water','Road connectivity','Rural infrastructure','Tourism & culture','Local civic services','Disaster preparedness'].map((x,i)=><div key={x}><span>0{i+1}</span><h3>{x}</h3><p>Key area for hill-region administration and community-facing development.</p></div>)}</div></Page>}
function PublicService(){return <Page eyebrow="05 / PUBLIC SERVICE" title={<>Responsibility translated into <em>action.</em></>}><div className="serviceHero"><div><span className="eyebrow">CURRENT ROLE</span><h2>Cabinet Minister<br/><em>Government of Uttarakhand</em></h2><p>Ram Singh Kaida was sworn in as a cabinet minister on 20 March 2026. The state’s urban development department lists him as the Hon’ble Urban Development Minister.</p></div><div className="roleCard"><Landmark/><span>STATE RESPONSIBILITY</span><strong>Uttarakhand</strong><small>Cabinet • Public administration</small></div></div><div className="serviceList">{service.map(([a,b],i)=><motion.div whileHover={{y:-5}} key={a}><div className="serviceIcon">0{i+1}</div><div><h3>{a}</h3><p>{b}</p></div><ArrowUpRight/></motion.div>)}</div></Page>}
function Media(){return <Page eyebrow="06 / MEDIA" title={<>Updates, statements & <em>public record.</em></>}><div className="mediaGrid">{['Cabinet oath • 20 March 2026','First visit to Bhimtal after cabinet induction','Review meeting on local infrastructure','Water and monsoon preparedness'].map((x,i)=><article key={x}><div className={'mediaImage mi'+i}><span>{String(i+1).padStart(2,'0')}</span></div><div className="mediaMeta"><span>PUBLIC UPDATE</span><time>2026</time></div><h3>{x}</h3><p>Follow developments and public-service activity through verified public reporting.</p><Link to="/contact">Request information <ArrowRight/></Link></article>)}</div><div className="mediaNote"><Play/><div><b>Media archive</b><p>Use the contact page to request a verified media or press resource.</p></div></div></Page>}
function Gallery(){return <Page eyebrow="07 / GALLERY" title={<>A visual archive of <em>public service.</em></>}><div className="galleryGrid">{[0,1,2,3,4,5].map((i)=><motion.div whileHover={{scale:1.02}} className={'galleryItem gi'+i} key={i}><img src="/ram-singh-kaida-reference.jpg" alt="Ram Singh Kaida portrait"/><div><span>PORTRAIT • {String(i+1).padStart(2,'0')}</span><b>Ram Singh Kaida</b></div></motion.div>)}</div><p className="galleryNote"><Images/> This gallery uses the supplied portrait as a placeholder archive frame. Replace individual frames with verified event photographs before publication.</p></Page>}
function Vision(){return <Page eyebrow="08 / VISION" title={<>A forward view of <em>service.</em></>}><div className="visionHero"><div><span className="eyebrow">THE NORTH STAR</span><h2>Development that feels visible in everyday life.</h2></div><p>A useful public-service website should make responsibilities, priorities, updates and ways to connect easy to understand. This section presents the themes of the profile without inventing project statistics.</p></div><div className="visionCards">{[['People first','Put accessibility, dignity and practical outcomes at the centre of public work.'],['Connected hills','Strengthen roads, water systems, civic services and digital access across difficult terrain.'],['Accountable delivery','Make progress easier to follow through clear updates, records and public communication.'],['Culture & nature','Protect the identity and natural character that make Kumaon distinctive.']].map(([a,b])=><div key={a}><ShieldCheck/><h3>{a}</h3><p>{b}</p></div>)}</div></Page>}
function Contact(){return <Page eyebrow="09 / CONTACT" title={<>Connect with the <em>public profile.</em></>}><div className="contactGrid"><div><span className="eyebrow">OFFICIAL CHANNEL</span><h2>For public, media & constituency enquiries.</h2><p>Use the information below as a starting point. For current office details, verify against the relevant Uttarakhand government department.</p><div className="contactCards"><a href="tel:+910135266644"><Phone/><span><small>OFFICE</small><b>+91 0135 266644</b></span></a><a href="mailto:info@udduk.uk.gov.in"><Mail/><span><small>DEPARTMENT EMAIL</small><b>info@udduk.uk.gov.in</b></span></a><div><Clock3/><span><small>OFFICE</small><b>Vidhan Sabha, Dehradun</b></span></div></div></div><form onSubmit={e=>e.preventDefault()}><label>Name<input placeholder="Your name"/></label><label>Email<input type="email" placeholder="you@example.com"/></label><label>Purpose<select defaultValue=""><option value="" disabled>Select enquiry type</option><option>Media</option><option>Public information</option><option>Constituency</option><option>Other</option></select></label><label>Message<textarea placeholder="How can we help?" rows={5}/></label><button className="btn primary" type="submit">Send enquiry <ArrowRight/></button></form></div><div className="disclaimer"><b>Important</b><p>This is an independent informational website concept. It is not the official website of the Uttarakhand Government or any elected office.</p></div></Page>}
function App(){return <Shell><Routes><Route path="/" element={<Home/>}/><Route path="/about" element={<About/>}/><Route path="/biography" element={<Biography/>}/><Route path="/journey" element={<Journey/>}/><Route path="/bhimtal" element={<Bhimtal/>}/><Route path="/public-service" element={<PublicService/>}/><Route path="/media" element={<Media/>}/><Route path="/gallery" element={<Gallery/>}/><Route path="/vision" element={<Vision/>}/><Route path="/contact" element={<Contact/>}/><Route path="*" element={<Home/>}/></Routes></Shell>}
createRoot(document.getElementById('root')!).render(<BrowserRouter><App/></BrowserRouter>);
